/*
 * SwaggerPetstoreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package io.swagger.petstore;

import io.apimatic.core.authentication.HeaderAuth;
import java.util.HashMap;

public class CustomHeaderAuthenticationManager extends HeaderAuth implements CustomHeaderAuthenticationCredentials {

    private String apiKey;

    /**
     * Constructor that sets custom header parameters.
     */
    public CustomHeaderAuthenticationManager(String apiKey) {
        super(new HashMap<String,String>() {
            private static final long serialVersionUID = 1L;
            {
                put("api_key", apiKey);
            }
        });

        this.apiKey = apiKey;
    }

    /**
     * String value for apiKey.
     * @return apiKey
     */
    public String getApiKey() {
        return apiKey;
    }

    /**
     * Checks if provided credentials matched with existing ones.
     * @param apiKey String value for credentials.
     * @return true if credentials matched.
     */
    public boolean equals(String apiKey) {
        return apiKey.equals(getApiKey());
    }

    /**
     * Converts this CustomHeaderAuthenticationManager into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "CustomHeaderAuthenticationManager [" + "apiKey=" + apiKey + "]";
    }

}
