/*
 * SwaggerPetstoreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package io.swagger.petstore;

/**
 * Interface for defining the behavior of CustomHeader Authentication.
 */
public interface CustomHeaderAuthenticationCredentials {

    /**
     * String value for apiKey.
     * @return apiKey
     */
    String getApiKey();

    /**
     * Checks if provided credentials matched with existing ones.
     * @param apiKey String value for credentials.
     * @return true if credentials matched.
     */
    boolean equals(String apiKey);
}
